### ISSUE TITLE
Cannot play completely

### ISSUE THREAD

**Issue by qq632756458** [moononournation/RGB565_video#12]
19:46:46.796 -> Guru Meditation Error: Core  1 panic'ed (LoadStoreError). Exception was unhandled.
19:46:46.836 -> 
19:46:46.836 -> Core  1 register dump:
19:46:46.836 -> PC      : 0x400d18f9  PS      : 0x00060f30  A0      : 0x800d9266  A1      : 0x3ffb27c0  
19:46:46.836 -> A2      : 0x3ffc0178  A3      : 0x00000800  A4      : 0x000000ff  A5      : 0x00000001  
19:46:46.836 -> A6      : 0x400002b7  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffb27a0  
19:46:46.836 -> A10     : 0x400002b8  A11     : 0x3ffb28b8  A12     : 0x00000800  A13     : 0x400002b8  
19:46:46.836 -> A14     : 0x04000000  A15     : 0xa201ca43  SAR     : 0x00000008  EXCCAUSE: 0x00000003  
19:46:46.876 -> EXCVADDR: 0x400002b7  LBEG    : 0x40085f75  LEND    : 0x40085f97  LCOUNT  : 0x00000000  
19:46:46.876 -> 
19:46:46.876 -> 
19:46:46.876 -> Backtrace:0x400d18f6:0x3ffb27c00x400d9263:0x3ffb2820 
19:46:46.876 -> 
19:46:46.876 -> 
19:46:46.876 -> 
19:46:46.876 -> 
19:46:46.876 -> ELF file SHA256: 0000000000000000
19:46:46.876 -> 
19:46:46.876 -> Rebooting...
19:46:46.876 -> ets Jun  8 2016 00:22:57
19:46:46.876 -> 
19:46:46.876 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:46:46.876 -> configsip: 0, SPIWP:0xee
19:46:46.876 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
19:46:46.876 -> mode:DIO, clock div:1
19:46:46.876 -> load:0x3fff0030,len:1240
19:46:46.916 -> load:0x40078000,len:13012
19:46:46.916 -> load:0x40080400,len:3648
19:46:46.916 -> entry 0x400805f8
19:46:47.652 -> MJPEG video start

**Comment by v5blueskyer** [comment]
内存不足，如果你用的esp32 wrover e，可以尝试使用片外存储。uint8_t *mjpeg_buf = (uint8_t *)ps_malloc(MJPEG_BUFFER_SIZE);       改成uint8_t *mjpeg_buf = (uint8_t *)ps_malloc(MJPEG_BUFFER_SIZE);
