### ISSUE TITLE
ESP32 resets

### ISSUE THREAD

**Issue by CodeOn-ArK** [moononournation/RGB565_video#13]
Whenever I upload the code along with the data as spiffs content, it keeps on resetting with this log:
```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4006897f  PS      : 0x00060530  A0      : 0x1a66660c  A1      : 0x3ffb1ec0  
A2      : 0x3ffbec00  A3      : 0x00000013  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x800d74a2  A9      : 0x3ffb1ea0  
A10     : 0x3ffb843c  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x0000000d  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000004  LBEG    : 0x400d4fb9  LEND    : 0x400d4fc6  LCOUNT  : 0x00000000  

```
I am using ST7789 with this configuration:

```
// ST7789 Display
#define TFT_BL 22
Arduino_DataBus *bus = new Arduino_ESP32SPI(15 /* DC */, 12 /* CS */, 18 /* SCK */, 23 /* MOSI */, 19 /* MISO */);
Arduino_ST7789 *gfx = new Arduino_ST7789(bus, -1 /* RST */, 2 /* rotation */, true /* IPS */, 240 /* width */, 240 /* height */, 0 /* col offset 1 */, 80 /* row offset 1 */);
```
Using ESP32 Dev module with 4MB Flash
and the following partition scheme : `1.2MB APP && 1.5MB SPIFFS`

**Comment by moononournation** [comment]
have you uploaded gif file to the flash?

**Comment by CodeOn-ArK** [comment]
yea, I did upload the gif in spiffs

**Comment by moononournation** [comment]
then comment out all FFat related code and uncomment all SPIFFS code?

**Comment by CodeOn-ArK** [comment]
I am testing this [code](https://github.com/moononournation/RGB565_video/blob/master/SPIFFS_GIF_video/SPIFFS_GIF_video.ino) there's no FFat related code there?

**Comment by moononournation** [comment]
ok, I have not maintain this example a long time ago. You may try the Arduino_GFX example first: https://github.com/moononournation/Arduino_GFX/tree/master/examples/ImgViewer/ImgViewerAnimatedGIF
