### ISSUE TITLE
ESP32-S3-WROOM-1U-N16R8能实现GIF播放吗？

### ISSUE THREAD

**Issue by LuBaker34** [moononournation/RGB565_video#18]
您好，我想请问这个库是否能使用ESP32-S3-WROOM-1U-N16R8实现GIF播放呢，因为我这ESP32S3型号板子报错，同样的代码使用其他型号就能通过编译。希望得到您的回复，谢谢。
![17A$ RRON( (0`)5(RI(UWE](https://github.com/moononournation/RGB565_video/assets/136065546/5fe90323-d055-4cde-a1eb-547a98c8e1b6)
![image](https://github.com/moononournation/RGB565_video/assets/136065546/93ab3bdf-9356-418b-8f59-fa68d9ade91f)

**Comment by moononournation** [comment]
seems your arduino-esp32 is not update

**Comment by LuBaker34** [comment]
May I ask which version of your arduino-esp32 is being used.

**Comment by moononournation** [comment]
simply get update in Arduino IDE

**Comment by LuBaker34** [comment]
I just upgraded the version, thank you very much.

**Comment by LuBaker34** [comment]
您好，再次请教您，我的屏幕是ILI9488,主控是ESP32-S3-WROOM-1U-N16R8，使用Arduino_GFX库无法使用是哪里有没有配置好的地方吗？我使用LovyanGFX和TFT_eSPI库是可以正常让屏幕显示颜色变化。
![image](https://github.com/moononournation/RGB565_video/assets/136065546/8a24fd97-906b-4522-b127-73a4827ed769)
![image](https://github.com/moononournation/RGB565_video/assets/136065546/9255cc0c-ae86-46cd-83e1-d03ad2c0676b)
![920fd70817330bd9b841af4f81cd8dd](https://github.com/moononournation/RGB565_video/assets/136065546/5b115ae8-3f4d-4e08-b84f-42da5e704181)

**Comment by moononournation** [comment]
SPI need 18bit driver

**Comment by LuBaker34** [comment]
I can use it normally after using 18bit, thank you very much.

**Comment by LuBaker34** [comment]
您好，我使用Arduino_GFX库中的ImgViewerAnimatedGIF事例，想要在屏幕上实现GIF的播放显示，串口打印下图的信息，是哪里需要注意吗？屏幕上没有反应。
![image](https://github.com/moononournation/RGB565_video/assets/136065546/13210bc5-233b-4877-8ada-1a1eb2ca992c)
![image](https://github.com/moononournation/RGB565_video/assets/136065546/45c4678b-c6ff-43e0-9323-a5fdb1ca5fce)

**Comment by moononournation** [comment]
if no display, please try PDQgraphicstest first

**Comment by LuBaker34** [comment]
I tried to compile PDQgraphicstest and the following situation occurred.
![image](https://github.com/moononournation/RGB565_video/assets/136065546/dbb74206-99d0-49d6-8bbf-5eaca7c7b199)

**Comment by LuBaker34** [comment]
![image](https://github.com/moononournation/RGB565_video/assets/136065546/eb871987-1b4e-49a1-b8fa-7752b5a9d7d8)

**Comment by LuBaker34** [comment]
显示没有问题，但是使用SD_GIF_video事例，GIF动画没有显示出来。请问使用GIF事例需要注意什么吗？
![83063dc062602c18611ffa405099c24](https://github.com/moononournation/RGB565_video/assets/136065546/3e53ff9a-7d60-447f-aed5-667b7e4d98ff)

**Comment by moononournation** [comment]
The figures are very slow, seems not enough to play animation.

**Comment by LuBaker34** [comment]
Can it be optimized, or is this an inherent limitation that cannot be changed?

**Comment by moononournation** [comment]
If you want to use ILI9488, try parallel 16 interface; If you want to use SPI, try ST7796.

**Comment by LuBaker34** [comment]
Thank you very much for your advice.

**Comment by LuBaker34** [comment]
Hello moononournation, can this library be used on ESP-IDF? How to link if possible? I'm trying to write CMAKELists.txt in the component to use this library, but I've reported an error so far and I haven't found such a file. Can you give me some advice? Thank you very much.
![image](https://github.com/moononournation/RGB565_video/assets/136065546/b2e78e5e-ae16-428b-a653-4a779ce7903d)
![image](https://github.com/moononournation/RGB565_video/assets/136065546/415427e3-9e43-4e82-a332-f243520b9815)

**Comment by moononournation** [comment]
Not tried. As mentioned in the name, this library is focus on Arduino IDE.

**Comment by LuBaker34** [comment]
Well, thank you for your reply.
