### ISSUE TITLE
About esp32s3 playback mjepg video constantly reboot problem

### ISSUE THREAD

**Issue by Xk-w** [moononournation/RGB565_video#20]
Playing videos using the library rgb565_video esp32s3 keeps rebooting, is it a problem of not enough memory? But already have psram on.

Here are the serial port messages:

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x40376ed4
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a68
entry 0x403c98d4
MJPEG video start

assert failed: spinlock_acquire spinlock.h:122 (result == core_id || result == SPINLOCK_FREE)

Backtrace: 0xfffffffe:0x8037ead8 |<-CORRUPTED

Backtrace: 0x403772c6:0x3fceb920 0x4037ce51:0x3fceb940 0x40382cad:0x3fceb960 0x403800f9:0x3fceba90 0x4037ddbe:0x3fcebad0 0x42004082:0x3fcebb10 0x42002ee1:0x3fcebe70 0x4200a612:0x3fcebee0

ELF file SHA256: 386e3ac5afb988d6

**Comment by moononournation** [comment]
This sample code developing while ESP32-S3 not yet release. You may try a newer sample at:
https://github.com/moononournation/MiniTV.git
