### ISSUE TITLE
PlatformIO IDE error

### ISSUE THREAD

**Issue by modi12jin** [moononournation/RGB565_video#3]
![esp32_vscode](https://user-images.githubusercontent.com/40233017/91178690-1671a780-e718-11ea-9fc9-aa3fd98fcb65.jpg)

> I have this kind of error message in the PlatformIO IDE environment

```
/home/jin/.platformio/lib/Arduino_GFX/Arduino_ESP32SPI_DMA.h:19:19: fatal error: unity.h: No such file or directory
```

**Comment by moononournation** [comment]
For those error that only appear in PlatformIO but not in Arduino IDE, I think you seek support at PlatformIO community can have better support.
