### ISSUE TITLE
Minor adaption SD_MMC examples if backlight is on GPIO 4

### ISSUE THREAD

**Issue by perlix** [moononournation/RGB565_video#6]
Trying to run the _SDMMC_MJPEG_video_PCM_audio_dualSPI_multitask_ example on a TTGO T4 V1.3 board, I noticed that 'SD_MMC.begin("/sdcard", true)' pulls GPIO 4 down, although SD_MMC in1-bit mode doesn't use that pin. However, GPIO 4 is TFT_BL on the TTGO T4, so nothing appeared on the screen. After putting the backlight control lines after SD.begin(...), it works great! Thanks for sharing your code.

**Comment by ghost** [comment]
I know this is 2 years old, but do you have a copy of the code you used to get this to work on the TTGO T4? It seems like the perfect hardware for the project, but I can't get anywhere with it. Did you mange to get both sound & video working?
